import type { PocketDeckCard, PocketDeckCategory } from "./model";

export const POCKET_DECK_CATEGORY_LABELS: Record<PocketDeckCategory, string> = {
  hotel: "Hotel",
  beach: "Beach",
  "food-drink": "Food and drink",
  paying: "Paying",
  problems: "Problems",
  "polite-exit": "Polite exits",
  understanding: "Help me understand",
};

export const POCKET_DECK_CATEGORIES = Object.entries(
  POCKET_DECK_CATEGORY_LABELS,
) as [PocketDeckCategory, string][];

function audioPath(speed: "normal" | "careful", id: string): string {
  return `/audio/pocket-deck/${speed}/${id}.m4a`;
}

export const CORE_POCKET_DECK_CARDS: readonly PocketDeckCard[] = [
  {
    id: "hotel-reservation",
    category: "hotel",
    englishIntent: "I have a reservation.",
    primaryItalian: "Ho una prenotazione.",
    shortItalian: "Ho una prenotazione.",
    likelyResponse: "A che nome?",
    likelyResponseEnglish: "What name is it under?",
    listenFor: ["nome · name", "documento · ID", "camera · room"],
    searchTerms: ["reservation", "booking", "check in", "hotel arrival", "room"],
    normalAudio: audioPath("normal", "hotel-reservation"),
    carefulAudio: audioPath("careful", "hotel-reservation"),
    audioTranscript: "Ho una prenotazione.",
    source: "core",
  },
  {
    id: "repeat-slower",
    category: "understanding",
    englishIntent: "Could you repeat that more slowly?",
    primaryItalian: "Può ripetere più lentamente, per favore?",
    shortItalian: "Più lentamente, per favore.",
    likelyResponse: "Certo, più lentamente.",
    likelyResponseEnglish: "Of course, more slowly.",
    listenFor: ["certo · of course", "ripeto · I’ll repeat", "lentamente · slowly"],
    searchTerms: ["repeat", "say again", "slow down", "more slowly", "speak slowly"],
    normalAudio: audioPath("normal", "repeat-slower"),
    carefulAudio: audioPath("careful", "repeat-slower"),
    audioTranscript: "Può ripetere più lentamente, per favore?",
    source: "core",
  },
  {
    id: "tired-tomorrow",
    category: "polite-exit",
    englishIntent: "I’m tired. Can we talk tomorrow?",
    primaryItalian: "Sono stanco. Possiamo parlarne domani?",
    shortItalian: "Ne parliamo domani?",
    likelyResponse: "Certo, riposati. A domani.",
    likelyResponseEnglish: "Of course—get some rest. See you tomorrow.",
    listenFor: ["certo · of course", "riposati · get some rest", "domani · tomorrow"],
    searchTerms: ["tired", "talk tomorrow", "end conversation", "good night", "leave"],
    normalAudio: audioPath("normal", "tired-tomorrow"),
    carefulAudio: audioPath("careful", "tired-tomorrow"),
    audioTranscript: "Sono stanco. Possiamo parlarne domani?",
    source: "core",
  },
  {
    id: "beach-one-chair-umbrella",
    category: "beach",
    englishIntent: "I need one beach chair and one umbrella.",
    primaryItalian: "Mi servono un lettino e un ombrellone.",
    shortItalian: "Un lettino e un ombrellone.",
    likelyResponse: "Per una o due persone?",
    likelyResponseEnglish: "For one or two people?",
    listenFor: ["una o due · one or two", "per oggi · for today", "euro · euros"],
    searchTerms: ["one chair umbrella", "beach chair", "sunbed", "umbrella", "rent beach gear"],
    normalAudio: audioPath("normal", "beach-one-chair-umbrella"),
    carefulAudio: audioPath("careful", "beach-one-chair-umbrella"),
    audioTranscript: "Mi servono un lettino e un ombrellone.",
    source: "core",
  },
  {
    id: "beach-one-not-two",
    category: "beach",
    englishIntent: "One beach chair, not two.",
    primaryItalian: "Un lettino, non due.",
    shortItalian: "Un lettino, non due.",
    likelyResponse: "Va bene, uno solo.",
    likelyResponseEnglish: "All right, just one.",
    listenFor: ["uno solo · only one", "due · two", "va bene · all right"],
    searchTerms: ["not two", "one chair", "only one", "solo traveler", "correct quantity"],
    normalAudio: audioPath("normal", "beach-one-not-two"),
    carefulAudio: audioPath("careful", "beach-one-not-two"),
    audioTranscript: "Un lettino, non due.",
    source: "core",
  },
  {
    id: "wrong-order",
    category: "food-drink",
    englishIntent: "This isn’t what I ordered.",
    primaryItalian: "Scusi, non è quello che ho ordinato.",
    shortItalian: "Non è il mio ordine.",
    likelyResponse: "Mi dispiace, controllo subito.",
    likelyResponseEnglish: "I’m sorry; I’ll check right away.",
    listenFor: ["mi dispiace · I’m sorry", "controllo · I’ll check", "subito · right away"],
    searchTerms: ["wrong order", "not what I ordered", "food mistake", "drink mistake", "order is wrong"],
    normalAudio: audioPath("normal", "wrong-order"),
    carefulAudio: audioPath("careful", "wrong-order"),
    audioTranscript: "Scusi, non è quello che ho ordinato.",
    source: "core",
  },
  {
    id: "extra-bill-item",
    category: "problems",
    englishIntent: "There is an extra item on the bill.",
    primaryItalian: "Scusi, c’è una voce in più sul conto.",
    shortItalian: "Questo non è mio.",
    likelyResponse: "Controllo il conto.",
    likelyResponseEnglish: "I’ll check the bill.",
    listenFor: ["conto · bill", "coperto · cover charge", "servizio · service"],
    searchTerms: ["extra charge", "bill is wrong", "extra item", "incorrect bill", "charged too much"],
    normalAudio: audioPath("normal", "extra-bill-item"),
    carefulAudio: audioPath("careful", "extra-bill-item"),
    audioTranscript: "Scusi, c’è una voce in più sul conto.",
    source: "core",
  },
  {
    id: "pay-by-card",
    category: "paying",
    englishIntent: "Can I pay by card?",
    primaryItalian: "Posso pagare con la carta?",
    shortItalian: "Con la carta, per favore.",
    likelyResponse: "Certo. Avvicini la carta.",
    likelyResponseEnglish: "Of course. Tap your card here.",
    listenFor: ["carta · card", "contanti · cash", "POS · card machine"],
    searchTerms: ["pay card", "credit card", "debit card", "card payment", "pay the bill"],
    normalAudio: audioPath("normal", "pay-by-card"),
    carefulAudio: audioPath("careful", "pay-by-card"),
    audioTranscript: "Posso pagare con la carta?",
    source: "core",
  },
  {
    id: "accept-suggestion",
    category: "food-drink",
    englishIntent: "That is fine, thank you.",
    primaryItalian: "Va bene così, grazie.",
    shortItalian: "Va bene.",
    likelyResponse: "Perfetto, arriva subito.",
    likelyResponseEnglish: "Perfect; it’ll be right out.",
    listenFor: ["perfetto · perfect", "subito · right away", "arriva · it’s coming"],
    searchTerms: ["that is fine", "accept suggestion", "okay thanks", "sounds good", "the usual"],
    normalAudio: audioPath("normal", "accept-suggestion"),
    carefulAudio: audioPath("careful", "accept-suggestion"),
    audioTranscript: "Va bene così, grazie.",
    source: "core",
  },
  {
    id: "later-thanks",
    category: "polite-exit",
    englishIntent: "Maybe later, thank you.",
    primaryItalian: "Magari più tardi, grazie.",
    shortItalian: "Più tardi, grazie.",
    likelyResponse: "Va bene, nessun problema.",
    likelyResponseEnglish: "All right, no problem.",
    listenFor: ["va bene · all right", "nessun problema · no problem", "più tardi · later"],
    searchTerms: ["later", "maybe later", "not now", "postpone", "polite exit"],
    normalAudio: audioPath("normal", "later-thanks"),
    carefulAudio: audioPath("careful", "later-thanks"),
    audioTranscript: "Magari più tardi, grazie.",
    source: "core",
  },
  {
    id: "dont-understand",
    category: "understanding",
    englishIntent: "I don’t understand.",
    primaryItalian: "Non capisco.",
    shortItalian: "Non capisco.",
    variation: "Non ho capito.",
    likelyResponse: "Le spiego.",
    likelyResponseEnglish: "I’ll explain it to you.",
    listenFor: ["spiego · I’ll explain", "vuol dire · it means", "ancora · again"],
    searchTerms: ["don't understand", "do not understand", "confused", "what does that mean", "help me understand"],
    normalAudio: audioPath("normal", "dont-understand"),
    carefulAudio: audioPath("careful", "dont-understand"),
    audioTranscript: "Non capisco.",
    source: "core",
  },
  {
    id: "how-much",
    category: "paying",
    englishIntent: "How much is it for today?",
    primaryItalian: "Quanto costa per oggi?",
    shortItalian: "Quanto costa?",
    likelyResponse: "Costa ventidue euro.",
    likelyResponseEnglish: "It costs twenty-two euros.",
    listenFor: ["costa · it costs", "euro · euros", "per oggi · for today"],
    searchTerms: ["how much", "price", "cost", "today's price", "what does it cost"],
    normalAudio: audioPath("normal", "how-much"),
    carefulAudio: audioPath("careful", "how-much"),
    audioTranscript: "Quanto costa per oggi?",
    source: "core",
  },
  {
    id: "apartment-key",
    category: "hotel",
    englishIntent: "I’m here for the key.",
    primaryItalian: "Sono qui per la chiave.",
    shortItalian: "Per la chiave.",
    likelyResponse: "La porta verde, al primo piano.",
    likelyResponseEnglish: "The green door, on the first floor.",
    listenFor: ["porta verde · green door", "primo piano · first floor", "chiave · key"],
    searchTerms: ["apartment key", "rental key", "check in apartment", "door", "access"],
    normalAudio: audioPath("normal", "apartment-key"),
    carefulAudio: audioPath("careful", "apartment-key"),
    audioTranscript: "Sono qui per la chiave.",
    source: "core",
  },
  {
    id: "bus-ticket",
    category: "understanding",
    englishIntent: "One ticket to Amalfi, please.",
    primaryItalian: "Un biglietto per Amalfi, per favore.",
    shortItalian: "Un biglietto per Amalfi.",
    likelyResponse: "Solo andata o andata e ritorno?",
    likelyResponseEnglish: "One way or round trip?",
    listenFor: ["solo andata · one way", "ritorno · return", "fermata · stop"],
    searchTerms: ["bus ticket", "ticket to Amalfi", "one way", "bus stop", "transport"],
    normalAudio: audioPath("normal", "bus-ticket"),
    carefulAudio: audioPath("careful", "bus-ticket"),
    audioTranscript: "Un biglietto per Amalfi, per favore.",
    source: "core",
  },
  {
    id: "pharmacy-bites",
    category: "problems",
    englishIntent: "I need something for mosquito bites.",
    primaryItalian: "Mi serve qualcosa per le punture di zanzara.",
    shortItalian: "Qualcosa per le punture.",
    likelyResponse: "Preferisce la crema o le compresse?",
    likelyResponseEnglish: "Would you prefer cream or tablets?",
    listenFor: ["crema · cream", "compresse · tablets", "pelle · skin"],
    searchTerms: ["pharmacy", "mosquito bites", "bite cream", "itch", "medicine"],
    normalAudio: audioPath("normal", "pharmacy-bites"),
    carefulAudio: audioPath("careful", "pharmacy-bites"),
    audioTranscript: "Mi serve qualcosa per le punture di zanzara.",
    source: "core",
  },
  {
    id: "how-does-it-work",
    category: "understanding",
    englishIntent: "How does this work?",
    primaryItalian: "Come funziona?",
    shortItalian: "Come funziona?",
    likelyResponse: "Prima inserisce due gettoni, poi preme il pulsante verde.",
    likelyResponseEnglish: "First insert two tokens, then press the green button.",
    listenFor: ["prima · first", "poi · then", "pulsante · button"],
    searchTerms: ["how does it work", "use machine", "instructions", "laundry", "washing machine"],
    normalAudio: audioPath("normal", "how-does-it-work"),
    carefulAudio: audioPath("careful", "how-does-it-work"),
    audioTranscript: "Come funziona?",
    source: "core",
  },
  {
    id: "how-long-does-it-take",
    category: "understanding",
    englishIntent: "How long does it take?",
    primaryItalian: "Quanto tempo ci vuole?",
    shortItalian: "Quanto tempo?",
    likelyResponse: "Circa trenta minuti.",
    likelyResponseEnglish: "About thirty minutes.",
    listenFor: ["circa · about", "minuti · minutes", "ore · hours"],
    searchTerms: ["how long", "duration", "time", "when ready", "wait"],
    normalAudio: audioPath("normal", "how-long-does-it-take"),
    carefulAudio: audioPath("careful", "how-long-does-it-take"),
    audioTranscript: "Quanto tempo ci vuole?",
    source: "core",
  },
  {
    id: "no-hot-water",
    category: "problems",
    englishIntent: "There is no hot water.",
    primaryItalian: "Non c’è acqua calda.",
    shortItalian: "Niente acqua calda.",
    likelyResponse: "Da quando?",
    likelyResponseEnglish: "Since when?",
    listenFor: ["da quando · since when", "tecnico · technician", "riparazione · repair"],
    searchTerms: ["no hot water", "water problem", "apartment repair", "shower", "maintenance"],
    normalAudio: audioPath("normal", "no-hot-water"),
    carefulAudio: audioPath("careful", "no-hot-water"),
    audioTranscript: "Non c’è acqua calda.",
    source: "core",
  },
  {
    id: "is-there-an-alternative",
    category: "problems",
    englishIntent: "Is there an alternative?",
    primaryItalian: "C’è un’alternativa?",
    shortItalian: "Un’alternativa?",
    likelyResponse: "Sì, abbiamo un’altra opzione.",
    likelyResponseEnglish: "Yes, we have another option.",
    listenFor: ["un’altra opzione · another option", "disponibile · available", "invece · instead"],
    searchTerms: ["alternative", "another option", "substitute", "unavailable", "instead"],
    normalAudio: audioPath("normal", "is-there-an-alternative"),
    carefulAudio: audioPath("careful", "is-there-an-alternative"),
    audioTranscript: "C’è un’alternativa?",
    source: "core",
  },
  {
    id: "temporary-stop",
    category: "understanding",
    englishIntent: "Where is the temporary stop?",
    primaryItalian: "Dov’è la fermata provvisoria?",
    shortItalian: "La fermata provvisoria?",
    likelyResponse: "In Piazza Alta, davanti alla farmacia.",
    likelyResponseEnglish: "In Piazza Alta, in front of the pharmacy.",
    listenFor: ["piazza · square", "davanti · in front", "farmacia · pharmacy"],
    searchTerms: ["temporary bus stop", "changed stop", "where is stop", "bus route", "detour"],
    normalAudio: audioPath("normal", "temporary-stop"),
    carefulAudio: audioPath("careful", "temporary-stop"),
    audioTranscript: "Dov’è la fermata provvisoria?",
    source: "core",
  },
  {
    id: "missing-document",
    category: "problems",
    englishIntent: "I don’t have the document with me.",
    primaryItalian: "Non ho il documento con me.",
    shortItalian: "Non ho il documento.",
    likelyResponse: "Ha il codice di ritiro?",
    likelyResponseEnglish: "Do you have the collection code?",
    listenFor: ["codice · code", "ritiro · collection", "consegna · delivery"],
    searchTerms: ["missing document", "no id", "parcel", "pickup code", "collection"],
    normalAudio: audioPath("normal", "missing-document"),
    carefulAudio: audioPath("careful", "missing-document"),
    audioTranscript: "Non ho il documento con me.",
    source: "core",
  },
  {
    id: "you-said-this-morning",
    category: "problems",
    englishIntent: "You said this morning.",
    primaryItalian: "Aveva detto stamattina.",
    shortItalian: "Aveva detto stamattina.",
    likelyResponse: "Ha ragione. Controllo subito.",
    likelyResponseEnglish: "You’re right. I’ll check immediately.",
    listenFor: ["ha ragione · you’re right", "controllo · I’ll check", "appuntamento · appointment"],
    searchTerms: ["you said", "this morning", "remind promise", "appointment", "commitment"],
    normalAudio: audioPath("normal", "you-said-this-morning"),
    carefulAudio: audioPath("careful", "you-said-this-morning"),
    audioTranscript: "Aveva detto stamattina.",
    source: "core",
  },
  {
    id: "refund-please",
    category: "paying",
    englishIntent: "I would like a refund, please.",
    primaryItalian: "Vorrei un rimborso, per favore.",
    shortItalian: "Un rimborso, per favore.",
    likelyResponse: "Certo. Ha il biglietto?",
    likelyResponseEnglish: "Of course. Do you have the ticket?",
    listenFor: ["biglietto · ticket", "rimborso · refund", "carta · card"],
    searchTerms: ["refund", "money back", "cancelled ticket", "ferry cancellation", "reimbursement"],
    normalAudio: audioPath("normal", "refund-please"),
    carefulAudio: audioPath("careful", "refund-please"),
    audioTranscript: "Vorrei un rimborso, per favore.",
    source: "core",
  },
  {
    id: "what-do-you-recommend",
    category: "food-drink",
    englishIntent: "What do you recommend?",
    primaryItalian: "Cosa mi consiglia?",
    shortItalian: "Cosa mi consiglia?",
    likelyResponse: "Le consiglio il panino caprese.",
    likelyResponseEnglish: "I recommend the caprese sandwich.",
    listenFor: ["consiglio · I recommend", "oggi · today", "euro · euros"],
    searchTerms: ["recommend", "suggestion", "what is good", "food recommendation", "vendor"],
    normalAudio: audioPath("normal", "what-do-you-recommend"),
    carefulAudio: audioPath("careful", "what-do-you-recommend"),
    audioTranscript: "Cosa mi consiglia?",
    source: "core",
  },
  {
    id: "can-get-credit",
    category: "problems",
    englishIntent: "Can I get a credit?",
    primaryItalian: "Posso avere un buono?",
    shortItalian: "Un buono?",
    likelyResponse: "Controllo il pagamento.",
    likelyResponseEnglish: "I’ll check the payment.",
    listenFor: ["pagamento · payment", "buono · credit", "rimborso · refund"],
    searchTerms: ["credit", "voucher", "weather closure", "compensation", "refund alternative"],
    normalAudio: audioPath("normal", "can-get-credit"),
    carefulAudio: audioPath("careful", "can-get-credit"),
    audioTranscript: "Posso avere un buono?",
    source: "core",
  },
  {
    id: "not-sure-yet",
    category: "polite-exit",
    englishIntent: "I’m not sure yet.",
    primaryItalian: "Non lo so ancora.",
    shortItalian: "Non lo so ancora.",
    likelyResponse: "Va bene, mi faccia sapere.",
    likelyResponseEnglish: "All right, let me know.",
    listenFor: ["va bene · all right", "sapere · know", "più tardi · later"],
    searchTerms: ["not sure", "don't know yet", "maybe", "undecided", "invitation"],
    normalAudio: audioPath("normal", "not-sure-yet"),
    carefulAudio: audioPath("careful", "not-sure-yet"),
    audioTranscript: "Non lo so ancora.",
    source: "core",
  },
  {
    id: "quiet-table",
    category: "food-drink",
    englishIntent: "I would prefer a quiet table.",
    primaryItalian: "Preferirei un tavolo tranquillo.",
    shortItalian: "Un tavolo tranquillo.",
    likelyResponse: "Certo, ho un tavolo dentro.",
    likelyResponseEnglish: "Of course, I have a table inside.",
    listenFor: ["dentro · inside", "fuori · outside", "rumore · noise"],
    searchTerms: ["quiet table", "restaurant seat", "less noise", "inside table", "table preference"],
    normalAudio: audioPath("normal", "quiet-table"),
    carefulAudio: audioPath("careful", "quiet-table"),
    audioTranscript: "Preferirei un tavolo tranquillo.",
    source: "core",
  },
  {
    id: "everything-settled",
    category: "problems",
    englishIntent: "Is everything settled?",
    primaryItalian: "È tutto a posto?",
    shortItalian: "Tutto a posto?",
    likelyResponse: "Sì, non c’è altro da pagare.",
    likelyResponseEnglish: "Yes, there is nothing else to pay.",
    listenFor: ["tutto · everything", "pagare · pay", "chiuso · closed"],
    searchTerms: ["everything settled", "all good", "checkout complete", "repair closed", "anything owed"],
    normalAudio: audioPath("normal", "everything-settled"),
    carefulAudio: audioPath("careful", "everything-settled"),
    audioTranscript: "È tutto a posto?",
    source: "core",
  },
  {
    id: "where-do-i-change",
    category: "understanding",
    englishIntent: "Where do I change?",
    primaryItalian: "Dove devo cambiare?",
    shortItalian: "Dove cambio?",
    likelyResponse: "A Vietri, poi dallo stallo tre.",
    likelyResponseEnglish: "At Vietri, then from stand three.",
    listenFor: ["Vietri · transfer place", "stallo · stand", "coincidenza · connection"],
    searchTerms: ["where change", "transfer", "change buses", "connection", "stand"],
    normalAudio: audioPath("normal", "where-do-i-change"),
    carefulAudio: audioPath("careful", "where-do-i-change"),
    audioTranscript: "Dove devo cambiare?",
    source: "core",
  },
  {
    id: "leaving-tomorrow",
    category: "hotel",
    englishIntent: "I’m leaving tomorrow.",
    primaryItalian: "Parto domani.",
    shortItalian: "Parto domani.",
    likelyResponse: "A che ora parte?",
    likelyResponseEnglish: "What time are you leaving?",
    listenFor: ["a che ora · what time", "chiavi · keys", "check-out · checkout"],
    searchTerms: ["leaving tomorrow", "departure", "checkout", "what time leave", "travel tomorrow"],
    normalAudio: audioPath("normal", "leaving-tomorrow"),
    carefulAudio: audioPath("careful", "leaving-tomorrow"),
    audioTranscript: "Parto domani.",
    source: "core",
  },
];

export const CORE_POCKET_DECK_CARD_IDS = new Set(
  CORE_POCKET_DECK_CARDS.map((card) => card.id),
);

export const CORE_POCKET_DECK_CARD_BY_ID = new Map(
  CORE_POCKET_DECK_CARDS.map((card) => [card.id, card]),
);

export const RECOVERY_POCKET_DECK_CARD_IDS = [
  "repeat-slower",
  "dont-understand",
] as const;
